name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Updated to latest stable version as of Feb 2025

      # Verify code formatting (optional quality check)
      - name: Check Formatting
        run: |
          gofmt -l .
          test -z "$(gofmt -l .)" || (echo "Code is not formatted with gofmt" && exit 1)

      # Build the program
      - name: Build
        run: go build -v -o locswap locswap.go # Specific to locswap.go, produces a binary

      # Test (placeholder for future tests)
      - name: Test
        run: go test -v ./... || echo "No tests found (optional step)"

      # Upload the binary as an artifact (optional)
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: locswap-binary
          path: locswap
